language: python
sudo: false
python:
  - "pypy"
  - "pypy3.3"
  - "3.7"
  - "3.6"
  - "3.5"
install:
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py develop
script:
  py.test -v --cov tinydb_serialization
after_success:
  coveralls
