language: python
sudo: false
python:
  - "pypy3"
  - "3.7"
  - "3.6"
  - "3.5"
before_install:
- pip install poetry
install:
  - poetry install
script:
  - poetry run py.test -v --cov tinydb_serialization
after_success:
  - poetry run coveralls
